spring:
  datasource:
    url: jdbc:h2:mem:mylittlecalculator;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: true
    defer-datasource-initialization: true


  h2:
    console:
      enabled: true
